#!/bin/bash -ex

source /env/libfuse-implementation

# compile libfuse-implementation
cd /src/libfuse-implementation
g++ -Wall main.c++ `pkg-config fuse --cflags --libs` -o /src/libfuse-implementation/main # pkg-config list include flags for apt packages
